"""Made event_slug unique constraint

Revision ID: 03e019a39519
Revises: 2279ebcf4357
Create Date: 2026-01-17 16:57:57.815237

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "03e019a39519"
down_revision: str | Sequence[str] | None = "2279ebcf4357"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_nba_games_event_slug", "nba_games", ["event_slug"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_nba_games_event_slug", "nba_games", type_="unique")
    # ### end Alembic commands ###
