"""Created indexes

Revision ID: 142ef8743284
Revises: b859206e71b1
Create Date: 2026-02-21 21:11:09.806684

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "142ef8743284"
down_revision: str | Sequence[str] | None = "b859206e71b1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("idx_event_markets_eventid_type", "event_markets", ["event_id", "market_type"], unique=False)
    op.create_index("idx_game_events_status_date", "game_events", ["game_status", "game_date"], unique=False)
    op.create_index("idx_market_prices_marketid_timestamp", "market_prices", ["market_id", "timestamp"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_market_prices_marketid_timestamp", table_name="market_prices")
    op.drop_index("idx_game_events_status_date", table_name="game_events")
    op.drop_index("idx_event_markets_eventid_type", table_name="event_markets")
    # ### end Alembic commands ###
