"""Changed price fields in nba_prices to nullable

Revision ID: 1b8a4664af2e
Revises: 8e64a6f0dd55
Create Date: 2026-01-15 16:28:20.699976

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1b8a4664af2e"
down_revision: str | Sequence[str] | None = "8e64a6f0dd55"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("nba_prices", "price_guest", existing_type=sa.NUMERIC(precision=10, scale=6), nullable=True)
    op.alter_column("nba_prices", "price_host", existing_type=sa.NUMERIC(precision=10, scale=6), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("nba_prices", "price_host", existing_type=sa.NUMERIC(precision=10, scale=6), nullable=False)
    op.alter_column("nba_prices", "price_guest", existing_type=sa.NUMERIC(precision=10, scale=6), nullable=False)
    # ### end Alembic commands ###
