"""Removed unnescessary index

Revision ID: 2279ebcf4357
Revises: 761afec2dccc
Create Date: 2026-01-15 22:34:53.215003

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2279ebcf4357"
down_revision: str | Sequence[str] | None = "761afec2dccc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_prices_market_ts"), table_name="nba_prices")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_prices_market_ts"), "nba_prices", ["market_id", "timestamp"], unique=False)
    # ### end Alembic commands ###
