"""Made unique constraints in nba_games

Revision ID: 2e829d8ead37
Revises: 534fc023c119
Create Date: 2026-01-18 17:05:32.941088

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2e829d8ead37"
down_revision: str | Sequence[str] | None = "534fc023c119"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_nba_markets_event_question", "nba_markets", ["event_id", "market_question"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_nba_markets_event_question", "nba_markets", type_="unique")
    # ### end Alembic commands ###
