"""Changed nba_prices timestamp field type

Revision ID: 3415beda879b
Revises: f8cff05e6324
Create Date: 2026-01-15 00:44:22.286223

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "3415beda879b"
down_revision: str | Sequence[str] | None = "f8cff05e6324"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
