"""Changed nullable fields

Revision ID: 39a32dd3cad3
Revises: e0fb74cef058
Create Date: 2026-01-15 21:22:56.973002

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "39a32dd3cad3"
down_revision: str | Sequence[str] | None = "e0fb74cef058"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("nba_games", "game_date", existing_type=sa.DATE(), nullable=False)
    op.alter_column("nba_games", "game_status", existing_type=sa.VARCHAR(length=50), nullable=False)
    op.alter_column("nba_games", "guest_team", existing_type=sa.VARCHAR(length=100), nullable=False)
    op.alter_column("nba_games", "guest_score", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("nba_games", "host_team", existing_type=sa.VARCHAR(length=100), nullable=False)
    op.alter_column("nba_games", "host_score", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("nba_markets", "market_question", existing_type=sa.VARCHAR(length=255), nullable=False)
    op.alter_column(
        "nba_markets",
        "order_min_price",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=10, scale=6),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "nba_markets",
        "order_min_price",
        existing_type=sa.Numeric(precision=10, scale=6),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    op.alter_column("nba_markets", "market_question", existing_type=sa.VARCHAR(length=255), nullable=True)
    op.alter_column("nba_games", "host_score", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("nba_games", "host_team", existing_type=sa.VARCHAR(length=100), nullable=True)
    op.alter_column("nba_games", "guest_score", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("nba_games", "guest_team", existing_type=sa.VARCHAR(length=100), nullable=True)
    op.alter_column("nba_games", "game_status", existing_type=sa.VARCHAR(length=50), nullable=True)
    op.alter_column("nba_games", "game_date", existing_type=sa.DATE(), nullable=True)
    # ### end Alembic commands ###
