"""Removed duplicate fields

Revision ID: 44bc2cf6acba
Revises: be639477ebf8
Create Date: 2026-01-15 20:27:06.322631

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "44bc2cf6acba"
down_revision: str | Sequence[str] | None = "be639477ebf8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_nba_games_event_id"), table_name="nba_games")
    op.drop_column("nba_games", "event_id")
    op.alter_column("nba_markets", "market_start", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=True)
    op.drop_index(op.f("ix_nba_markets_market_id"), table_name="nba_markets")
    op.drop_column("nba_markets", "market_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("nba_markets", sa.Column("market_id", sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index(op.f("ix_nba_markets_market_id"), "nba_markets", ["market_id"], unique=True)
    op.alter_column("nba_markets", "market_start", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=False)
    op.add_column("nba_games", sa.Column("event_id", sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index(op.f("ix_nba_games_event_id"), "nba_games", ["event_id"], unique=True)
    # ### end Alembic commands ###
