"""Created initial schema

Revision ID: 47ec82af50c0
Revises:
Create Date: 2026-01-11 21:13:25.106911

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "47ec82af50c0"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nba_games",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("event_slug", sa.String(length=255), nullable=False),
        sa.Column("event_title", sa.String(length=255), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=True),
        sa.Column("game_date", sa.Date(), nullable=True),
        sa.Column("game_status", sa.String(length=50), nullable=True),
        sa.Column("game_is_live", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("guest_team", sa.String(length=100), nullable=True),
        sa.Column("guest_score", sa.Integer(), nullable=True),
        sa.Column("host_team", sa.String(length=100), nullable=True),
        sa.Column("host_score", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_nba_games_event_id"), "nba_games", ["event_id"], unique=True)
    op.create_table(
        "nba_markets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("market_id", sa.Integer(), nullable=False),
        sa.Column("market_type", sa.String(length=50), nullable=True),
        sa.Column("market_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("market_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("order_min_price", sa.Float(), nullable=True),
        sa.Column("order_min_size", sa.Float(), nullable=True),
        sa.Column("token_id_guest", sa.String(length=100), nullable=False),
        sa.Column("token_id_host", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["nba_games.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_nba_markets_market_id"), "nba_markets", ["market_id"], unique=True)
    op.create_table(
        "nba_prices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("market_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("price_guest", sa.Float(), nullable=False),
        sa.Column("price_host", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["market_id"], ["nba_markets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("market_id", "timestamp", name="uq_market_price_market_ts"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("nba_prices")
    op.drop_index(op.f("ix_nba_markets_market_id"), table_name="nba_markets")
    op.drop_table("nba_markets")
    op.drop_index(op.f("ix_nba_games_event_id"), table_name="nba_games")
    op.drop_table("nba_games")
    # ### end Alembic commands ###
