"""Created normilized nba_games.game_status

Revision ID: 505d38e78a31
Revises: 9ed9a7435661
Create Date: 2026-01-18 17:55:46.368659

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "505d38e78a31"
down_revision: str | Sequence[str] | None = "9ed9a7435661"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("nba_games", sa.Column("game_status", sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("nba_games", "game_status")
    # ### end Alembic commands ###
