"""Mage game scores nullable

Revision ID: 761afec2dccc
Revises: c3b2aee0ea54
Create Date: 2026-01-15 21:53:11.235454

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "761afec2dccc"
down_revision: str | Sequence[str] | None = "c3b2aee0ea54"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("nba_games", "guest_score", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("nba_games", "host_score", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("nba_games", "host_score", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("nba_games", "guest_score", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
