"""Changed nba_prices fields types

Revision ID: 8e64a6f0dd55
Revises: 3415beda879b
Create Date: 2026-01-15 15:53:40.618014

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8e64a6f0dd55"
down_revision: str | Sequence[str] | None = "3415beda879b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "nba_prices",
        "timestamp",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.Integer(),
        existing_nullable=False,
        postgresql_using="EXTRACT(EPOCH FROM timestamp)::integer",
    )
    op.alter_column(
        "nba_prices",
        "price_guest",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=10, scale=6),
        existing_nullable=False,
    )
    op.alter_column(
        "nba_prices",
        "price_host",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=10, scale=6),
        existing_nullable=False,
    )
    op.create_index("ix_prices_market_ts", "nba_prices", ["market_id", "timestamp"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_prices_market_ts", table_name="nba_prices")
    op.alter_column(
        "nba_prices",
        "price_host",
        existing_type=sa.Numeric(precision=10, scale=6),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    op.alter_column(
        "nba_prices",
        "price_guest",
        existing_type=sa.Numeric(precision=10, scale=6),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    op.alter_column(
        "nba_prices",
        "timestamp",
        existing_type=sa.Integer(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        postgresql_using="to_timestamp(timestamp)",
    )
    # ### end Alembic commands ###
