"""nba_games.game_status -> game_period, removed game_is_live

Revision ID: 9ed9a7435661
Revises: 2e829d8ead37
Create Date: 2026-01-18 17:52:02.840949

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9ed9a7435661"
down_revision: str | Sequence[str] | None = "2e829d8ead37"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("nba_games", sa.Column("game_period", sa.String(length=20), nullable=True))
    op.drop_column("nba_games", "game_is_live")
    op.drop_column("nba_games", "game_status")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("nba_games", sa.Column("game_status", sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column(
        "nba_games",
        sa.Column("game_is_live", sa.BOOLEAN(), server_default=sa.text("false"), autoincrement=False, nullable=False),
    )
    op.drop_column("nba_games", "game_period")
    # ### end Alembic commands ###
