"""Made nba_games.game_status non-nullable

Revision ID: abb6767430d2
Revises: 505d38e78a31
Create Date: 2026-01-18 18:37:11.775740

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "abb6767430d2"
down_revision: str | Sequence[str] | None = "505d38e78a31"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("nba_games", "game_status", existing_type=sa.VARCHAR(length=20), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("nba_games", "game_status", existing_type=sa.VARCHAR(length=20), nullable=True)
    # ### end Alembic commands ###
