"""created market_orders table

Revision ID: b859206e71b1
Revises: aaab30fefff7
Create Date: 2026-01-23 14:35:01.320056

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b859206e71b1"
down_revision: str | Sequence[str] | None = "aaab30fefff7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "market_orders",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("market_id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.String(length=100), nullable=False),
        sa.Column("strategy", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("side", sa.String(length=5), nullable=False),
        sa.Column("price", sa.Numeric(precision=10, scale=6), nullable=False),
        sa.Column("size", sa.Numeric(precision=10, scale=6), nullable=False),
        sa.Column("filled", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("ts_expiration", sa.Integer(), nullable=True),
        sa.Column("ts_created", sa.Integer(), nullable=False),
        sa.Column("ts_updated", sa.Integer(), nullable=True),
        sa.Column("ts_canceled", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["market_id"], ["event_markets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("market_id", "order_id", "ts_created", name="uq_market_orders_market_order_ts_created"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("market_orders")
    # ### end Alembic commands ###
