"""Update NBA market models

Revision ID: ba89ceaaabfe
Revises: eb722c5706dc
Create Date: 2026-01-06 14:29:51.229771

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ba89ceaaabfe"
down_revision: str | Sequence[str] | None = "eb722c5706dc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nba_market_games",
        sa.Column("market_id", sa.Integer(), nullable=False),
        sa.Column("market_slug", sa.String(length=255), nullable=False),
        sa.Column("market_title", sa.String(length=255), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=True),
        sa.Column("game_start_date", sa.DateTime(), nullable=True),
        sa.Column("game_elapsed_time", sa.String(length=50), nullable=True),
        sa.Column("game_score", sa.String(length=20), nullable=True),
        sa.Column("game_period", sa.String(length=50), nullable=True),
        sa.Column("game_is_live", sa.Boolean(), nullable=False),
        sa.Column("guest_team", sa.String(length=100), nullable=True),
        sa.Column("guest_score", sa.Integer(), nullable=True),
        sa.Column("host_team", sa.String(length=100), nullable=True),
        sa.Column("host_score", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("market_id"),
    )
    op.create_table(
        "nba_market_prices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("market_id", sa.Integer(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(), nullable=False),
        sa.Column("guest_price", sa.Float(), nullable=False),
        sa.Column("host_price", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["market_id"], ["nba_market_games.market_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("market_id", "recorded_at", name="uq_nba_market_price_market_id_recorded_at"),
    )
    op.drop_table("market_prices")
    op.drop_table("market_history")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "market_prices",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("market_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("recorded_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column(
            "host_price",
            sa.DOUBLE_PRECISION(precision=53),
            server_default=sa.text("'0'::double precision"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "guest_price",
            sa.DOUBLE_PRECISION(precision=53),
            server_default=sa.text("'0'::double precision"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["market_id"], ["market_history.market_id"], name=op.f("market_prices_market_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("market_prices_pkey")),
    )
    op.create_table(
        "market_history",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("game_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("market_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("market_slug", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column("market_title", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column("host_team", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("guest_team", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("host_points", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("guest_points", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("overtimes", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("start_time", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("end_time", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("host_clob_token_id", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("guest_clob_token_id", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("market_history_pkey")),
        sa.UniqueConstraint(
            "market_id",
            name=op.f("market_history_market_id_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.drop_table("nba_market_prices")
    op.drop_table("nba_market_games")
    # ### end Alembic commands ###
