"""Removed before_update event from nba_prices

Revision ID: be639477ebf8
Revises: 1b8a4664af2e
Create Date: 2026-01-15 17:12:04.239454

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "be639477ebf8"
down_revision: str | Sequence[str] | None = "1b8a4664af2e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
