"""Removed nullable fields in nba_markets

Revision ID: e0fb74cef058
Revises: 44bc2cf6acba
Create Date: 2026-01-15 20:57:02.495948

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e0fb74cef058"
down_revision: str | Sequence[str] | None = "44bc2cf6acba"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("nba_markets", sa.Column("market_question", sa.String(length=255), nullable=True))
    op.alter_column("nba_markets", "market_type", existing_type=sa.VARCHAR(length=50), nullable=False)
    op.alter_column("nba_markets", "market_start", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=False)
    op.alter_column("nba_markets", "market_end", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=False)
    op.alter_column("nba_markets", "order_min_price", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=False)
    op.alter_column("nba_markets", "order_min_size", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("nba_markets", "order_min_size", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=True)
    op.alter_column("nba_markets", "order_min_price", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=True)
    op.alter_column("nba_markets", "market_end", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=True)
    op.alter_column("nba_markets", "market_start", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=True)
    op.alter_column("nba_markets", "market_type", existing_type=sa.VARCHAR(length=50), nullable=True)
    op.drop_column("nba_markets", "market_question")
    # ### end Alembic commands ###
