"""create market tables

Revision ID: eb722c5706dc
Revises:
Create Date: 2025-12-29 20:22:11.480712

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eb722c5706dc"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "market_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("game_date", sa.Date(), nullable=False),
        sa.Column("market_id", sa.Integer(), nullable=False),
        sa.Column("market_slug", sa.String(length=100), nullable=True),
        sa.Column("market_title", sa.String(length=100), nullable=True),
        sa.Column("host_team", sa.String(length=100), nullable=False),
        sa.Column("guest_team", sa.String(length=100), nullable=False),
        sa.Column("host_points", sa.Integer(), nullable=False),
        sa.Column("guest_points", sa.Integer(), nullable=False),
        sa.Column("overtimes", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=True),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.Column("host_clob_token_id", sa.String(length=100), nullable=False),
        sa.Column("guest_clob_token_id", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("market_id"),
    )
    op.create_table(
        "market_prices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("market_id", sa.Integer(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(), nullable=False),
        sa.Column("host_price", sa.Float(), server_default="0", nullable=False),
        sa.Column("guest_price", sa.Float(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(["market_id"], ["market_history.market_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("market_prices")
    op.drop_table("market_history")
    # ### end Alembic commands ###
