"""Added autoincrementing PKs

Revision ID: f8cff05e6324
Revises: 47ec82af50c0
Create Date: 2026-01-12 00:29:22.360858

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "f8cff05e6324"
down_revision: str | Sequence[str] | None = "47ec82af50c0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
